name: Test Docker Build

on:
  push:
    branches:
      - main
      - test-docker

jobs:
  test:
    name: Test Docker build
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Build Docker image
        run: |
          docker build -t stdpipe/stdpipe . && docker push stdpipe/stdpipe

      # - name: Start containers
      #   run: |
      #     docker-compose up -d
